### PR TITLE
fixed species sorting, added query to footer

### PR DESCRIPTION
**Pull request by jdrever**
Big step forward with species seaching - once the existing fsort parameter is removed, the search works as expected.  Have added the API query to the footer for reference.

### CODE REVIEW

**Comment by charlesroper** [comment]
Good idea about adding the query to the footer. I wonder if it's possible to log debug messages like this out to the CI debug bar thingy?

**Comment by charlesroper** [comment]
Why does _removing_ the fsort fix the issue?

**Comment by jdrever** [comment]
Absolutely no idea 😊  I’m not sure what fsort is intended to do – not documented – wondered if it was facet sort, but not sure what that would actually do.

Just leaves sort=year which then seems to work properly.

**Comment by jdrever** [comment]
The CI debug bar thingy already has $queryUrl, plus all current variables – very helpful, actually.

**Pull request merged**
