### PR TITLE
Common name search (plus initial implementation of sort)

### LINKED ISSUE #22: 4.1.2 Species Search: If Common is selected, only the species with common names will be searched and shown. Any species without common names should not be included in the search results.
See https://github.com/jdrever/ShropBotSoc/blob/develop/docs/specification.md#412-species-search

### PR DESCRIPTION
**Pull request by jdrever**
Another easy change, BUT it seems the NBN API is ignoring the sort field.

https://records-ws.nbnatlas.org/explore/group/ALL_SPECIES?q=data_resource_uid:dr782&fq=common_name:Ivy*%20AND%20species_group:Plants&facets=&sort=common_name&fsort=&pageSize=9

Gives the same results as 

https://records-ws.nbnatlas.org/explore/group/ALL_SPECIES?q=data_resource_uid:dr782&fq=common_name:Ivy*%20AND%20species_group:Plants&facets=&sort=&fsort=&pageSize=9

And even

https://records-ws.nbnatlas.org/explore/group/ALL_SPECIES?q=data_resource_uid:dr782&fq=common_name:Ivy*%20AND%20species_group:Plants&facets=&sort=XXX&fsort=&pageSize=9

### CODE REVIEW

**Comment by charlesroper** [comment]
This is all looking great @jdrever.

I think a change of workflow is needed though. If we keep making cumulative changes without first merging the PRs it becomes hard to see the commits relevant to the PR. E.g. your small changes in these list two commits look much bigger than they really are. 

So I suggest still doing a PR with the changes, describe them etc, but then merge in right away. If you tag me in on the PR I can see it, switch to it, and comment on it, etc. But there's no need to wait for me to formally review and so require long cumulative branching.

What do you think?

**Review by charlesroper — APPROVED** [review]
Approved! No comments for now - will review properly over weekend.

**Comment by charlesroper** [comment]
Do you think we should get in touch with the NBN about the apparent sorting problems and the to ask if they have some sort of taxonomic ordering?

Ask on the forum perhaps?

https://forums.nbn.org.uk/viewforum.php?id=46

**Comment by charlesroper** [comment]
Some more thoughts on merging right away vs cumulatively adding to branches.

I re-read this on the GitHub Flow:

https://githubflow.github.io/

It's a good article - very clear.

They do require a review for each PR as part of their lightweight process, but their situation is very different from ours: they are deploying to live when they merge, whereas we are merely adding to a develop branch. So we can afford to be more free and fast with the merges, I think.

I think this is probably going to be easier to deal with than the cumulative approach which I think we both have found a bit confusing/unwieldy.

**Comment by jdrever** [comment]
OK, so just to be clear, the process is:


  1.  Develop on a local branch.
  2.  When complete, push to jdrever repository.
  3.  If requires discussion, raise a PR otherwise, merge to develop on the remote and pull develop locally and loop back to 1

Does that work?

**Comment by jdrever** [comment]
Ah, reading earlier email.  So always raise a PR.

From: James Drever
Sent: 03 April 2021 15:41
To: jdrever/ShropBotSoc ***@***.***>; jdrever/ShropBotSoc ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [jdrever/ShropBotSoc] Common name search (plus initial implementation of sort) (#53)

OK, so just to be clear, the process is:


  1.  Develop on a local branch.
  2.  When complete, push to jdrever repository.
  3.  If requires discussion, raise a PR otherwise, merge to develop on the remote and pull develop locally and loop back to 1

Does that work?

**Comment by charlesroper** [comment]
Just seen there's a merge conflict on this. Looks like the changes from `common-name-search` are the lines you need.

>  1.  Develop on a local branch.
>  2.  When complete, push to jdrever repository.
>  3.  If requires discussion, raise a PR otherwise, merge to develop on the remote and pull develop locally and loop back to 1

More like this:

1. Develop on local branch
2. Push that branch regularly (as a backup)
3. Raise a PR when you want to discuss or merge - make a call as to whether you think it needs reviewing or discussing before merging
4. Either wait for review or merge immediately

If you're waiting for a review, seems like it is best to start a new branch off `develop`. Still not sure if it is then best to merge in changes from other branches (if you need them). But it seems that getting changes into the main `develop` branch as soon as possible keeps things simple as possible.

**Comment by jdrever** [comment]
Yep sorted the merge conflicts (there were several on the 4 pull requests) and merged to develop.  Have also pushed to captain-magenta.

Ok lets try with the process you’ve laid out.  I’ll try and plan things a bit so cumulative/structural stuff is simplified/separated out and can be merged to develop.

For info: currently working on pagination..

**Pull request merged**
