### PR TITLE
4.2 frontend records for single species

### PR DESCRIPTION
**Pull request by charlesroper**
This is ready to merge. See commit messages for full lowdown of what's in this PR.

### CODE REVIEW

**Comment by jdrever** [comment]
@charlesroper do you think we need/can do anything about the table on phone-size screens? 
image

**Comment by charlesroper** [comment]
Yes, need to hide the non essential columns same as the search page. But that can be in the next PR.

**Review by jdrever — APPROVED** [review]
Looks good Charles :)  Have noted table layout on phone, and also wondering if we need to remember the tab choice when the user returns?

**Comment by charlesroper** [comment]
Returns from where? Another page?

**Comment by jdrever** [comment]
Yes, whatever page they link to from this one.

**Comment by charlesroper** [comment]
@jdrever got it. Could use cookies, but probably easier to use localStorage or sessionStorage ([see here](https://vanillajstoolkit.com/reference/#Browser-Storage)).

Current thinking:

- Don't need to store if Map tab is selected because it is default
- Store state when Data is selected
- Remove state when Map is selected
- On page load check tab state and trigger if it exists

**Comment by jdrever** [comment]
Yep, but don't worry too much about it at this stage, don't think we need to deliver it by end of the month, I think it's a refinement.
________________________________

**Pull request merged**
